spin_manifest_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "A Spin template for building Docusaurus sites"
name = "docusaurus_template"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "Docusaurus Template"
files = [ { source = "my-website/build", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
watch = ["src/**", "static/**", "docs/**", "blog/**"]
command = "npm run build"
workdir = "my-website"
